spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: ${DDL_TYPE}
    database-platform: org.hibernate.dialect.MariaDBDialect

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_SECRET}

management:
  health:
    db:
      enabled: true  # 데이터베이스 연결 상태 확인
    redis:
      enabled: true # redis 연결 상태 확인

jwt:
  secret: ${TACO_JWT_SECRET}
  expiration: ${TACO_JWT_EXP}
server:
  port: ${TACO_AUTH_PORT}

aws:
  s3:
    bucket-name: ${AWS_S3_BUCKET_NAME}
    folder: ${AWS_S3_FOLDER_PATH}
    access-key: ${AWS_S3_IAM_ACCESS_KEY}
    secret-key: ${AWS_S3_IAM_SECRET_KEY}
    region: ${AWS_S3_REGION}





