spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/tacobank_db
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MariaDBDialect

  data:
    redis:
      host: localhost
      port: 6379
      password: 1234

management:
  health:
    db:
      enabled: true  # 데이터베이스 연결 상태 확인
    redis:
      enabled: true # redis 연결 상태 확인

jwt:
  secret:
  expiration:
server:
  port: 9001



