spring:
  application:
    name: tacobank_auth_server
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://{DB_HOST}:{DB_PORT}/{DB_NAME}
    username: {DB_USERNAME}
    password: {DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.MariaDBDialect

management:
  prometheus:
    metrics:
      export:
        enabled: true
  endpoint:
    health:
      enabled: true
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
  health:
    db:
      enabled: true  # 데이터베이스 연결 상태 확인

server:
  port: 9001