replicaCount: 1

image:
  repository: 485298580046.dkr.ecr.ap-northeast-2.amazonaws.com/taco_auth
  tag: latest
  pullPolicy: Always

service:
  type: NodePort
  port: 80
  targetPort: 8080
  nodePort: 30080

secret:
  apiKey: "my-secret-api-key"
  dbPassword: "super-secure-password"

config:
  environment: production
  logLevel: info
